#!/usr/bin/env python3
"""Build the test corpus used to verify watermarks-remover.

Creates files carrying known, counted provenance marks so that detection and
removal can be checked against an exact expected result.
"""
import struct, zlib, zipfile, pathlib

OUT = pathlib.Path(__file__).parent / "corpus"
OUT.mkdir(exist_ok=True)

# 1. Markdown: 8 invisible / format / homoglyph codepoints (Layer A targets)
(OUT / "sample.md").write_text(
    "Dies ist ein Testabsatz.​\n"
    "Zweite Zeile mit‍ Zero-Width-Joiner.\n"
    "Dritte⁠Zeile mit Word-Joiner.\n"
    "Vierte Zeile mit No-Break-Space.\n"
    "Fünfte Zeile‮mit RLO-Bidi.‬\n"
    "Sechste Zeile mit VS️ Variation Selector.\n"
    "Siebte Zeile mit⁡ Function Application.\n",
    encoding="utf-8",
)

# 2. PNG: tEXt + iTXt(XMP) + a C2PA-style caBX chunk
def _chunk(typ, data):
    c = typ + data
    return struct.pack(">I", len(data)) + c + struct.pack(">I", zlib.crc32(c) & 0xFFFFFFFF)

raw = b"".join(b"\x00" + b"\xff\x00\x00" * 2 for _ in range(2))
png = b"\x89PNG\r\n\x1a\n" + _chunk(b"IHDR", struct.pack(">IIBBBBB", 2, 2, 8, 2, 0, 0, 0))
png += _chunk(b"tEXt", b"Software\x00Claude (Anthropic)")
png += _chunk(b"tEXt", b"Author\x00Konstantin")
png += _chunk(b"iTXt", b"XML:com.adobe.xmp\x00\x00\x00\x00\x00<x:xmpmeta><dc:creator>AI</dc:creator></x:xmpmeta>")
png += _chunk(b"caBX", b"c2pa-fake-manifest-store-bytes")
png += _chunk(b"IDAT", zlib.compress(raw)) + _chunk(b"IEND", b"")
(OUT / "sample.png").write_bytes(png)

# 3. DOCX: AI attribution in docProps + ZWSP in body text
CT = ('<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
      '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
      '<Default Extension="xml" ContentType="application/xml"/>'
      '<Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>'
      '{core}</Types>')
CORE_OVR = '<Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/>'
RELS = ('<?xml version="1.0"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
        '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>{core}</Relationships>')
CORE_REL = '<Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/>'

def _docx(path, body, with_core):
    with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as z:
        z.writestr("[Content_Types].xml", CT.format(core=CORE_OVR if with_core else ""))
        z.writestr("_rels/.rels", RELS.format(core=CORE_REL if with_core else ""))
        if with_core:
            z.writestr("docProps/core.xml",
                '<?xml version="1.0"?><cp:coreProperties '
                'xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" '
                'xmlns:dc="http://purl.org/dc/elements/1.1/"><dc:creator>Claude (Anthropic)</dc:creator>'
                '<cp:lastModifiedBy>Claude</cp:lastModifiedBy>'
                '<dc:description>Generated by AI</dc:description></cp:coreProperties>')
        z.writestr("word/document.xml",
            '<?xml version="1.0"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">'
            f'<w:body><w:p><w:r><w:t>{body}</w:t></w:r></w:p></w:body></w:document>')

_docx(OUT / "sample.docx", "Hallo​Welt mit Zero-Width.", with_core=True)
# Isolates the /inspect false negative: ZWSP only, no docProps at all.
_docx(OUT / "zw_only.docx", "Hallo​Welt​mit​ZWSP.", with_core=False)

# 4. SVG + HTML
(OUT / "sample.svg").write_text(
    '<svg xmlns="http://www.w3.org/2000/svg"><metadata><dc:creator '
    'xmlns:dc="http://purl.org/dc/elements/1.1/">Claude</dc:creator></metadata>'
    '<!-- Generated by AI --><rect width="1" height="1"/></svg>', encoding="utf-8")
(OUT / "sample.html").write_text(
    '<html><head><meta name="generator" content="Claude (Anthropic)"></head>'
    '<body><p>Test​mit ZWSP.</p></body></html>', encoding="utf-8")

print(f"corpus written to {OUT}")
for f in sorted(OUT.iterdir()):
    print(f"  {f.name:16} {f.stat().st_size:6} bytes")
